project:
  type: website
  output-dir: docs

website:
  title: "Me"
  navbar:
    left:

      - href: index.qmd
        text: Home
      - text: "CV"
        
      - about.qmd
      
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

