project:
  type: website
  output-dir: docs

website:
  title: "Melanie Niu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "CV"
        href: cv-academic-MN.pdf
      - about.qmd
      
  
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

